
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'
pod 'AFNetworking'
pod 'MJRefresh','~> 3.1.0'
pod 'MBProgressHUD' ,'~> 0.9.2'
pod 'XMPPFramework','~> 3.6.6'
pod 'MOBFoundation_IDFA', '~> 1.5.1'
pod 'SMSSDK', '~> 2.0.4'
pod 'SVProgressHUD','~>1.1.3'
pod 'SBJson' , '~> 3.1.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'UMengSocial', '~> 5.0'
pod 'SDAutoLayout'




target '更美丽' do
    
end

